<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\GroqTripPlannerService;
use App\Models\Trip; // استدعاء الموديل

class AiTripController extends Controller
{
    protected $groqService;

    public function __construct(GroqTripPlannerService $groqService)
    {
        $this->groqService = $groqService;
    }

    /**
     * يعرض صفحة إنشاء الرحلة بالذكاء الاصطناعي.
     */
    public function create()
    {
        return view('trips.ai.create');
    }

    /**
     * يتلقى بيانات النموذج ويتصل بـ Groq API لتوليد خطة الرحلة عبر الخدمة.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function generate(Request $request)
    {
        // 1. التحقق من صحة المدخلات
        $validated = $request->validate([
            'description' => 'required|string|max:1000',
            'travelers_number' => 'required|integer|min:1',
            'budget' => 'nullable|numeric',
            'duration' => 'required|integer|min:1',
            'language' => 'nullable|in:en,ar', 
        ]);

        // 2. تجميع البيانات للخدمة
        $tripData = [
            'description' => $validated['description'],
            'travelers_number' => $validated['travelers_number'],
            'budget' => $validated['budget'],
            'duration' => $validated['duration'],
        ];
        
        $language = $validated['language'] ?? 'en'; 

        // 3. استدعاء الخدمة لتوليد خطة الرحلة
        $tripPlan = $this->groqService->generateTripPlan($tripData, $language);

        // 4. معالجة الرد وحفظه
        if ($tripPlan) {
            // **الخطوة الجديدة: حفظ الرحلة في قاعدة البيانات**
            $trip = Trip::create([
                'user_id' => auth()->id(), // نفترض أن المستخدم مسجل الدخول
                'name' => 'AI Generated Trip: ' . substr($validated['description'], 0, 50) . '...', // اسم مؤقت
                'description' => $validated['description'],
                'travelers_number' => $validated['travelers_number'],
                'budget' => $validated['budget'],
                // بما أننا لا نملك تواريخ محددة، سنستخدم تواريخ وهمية أو نتركها فارغة
                // لكن يجب أن يكون الحقلان start_date و end_date غير مطلوبين في قاعدة البيانات
                // أو نستخدم تاريخ اليوم وتاريخ اليوم + المدة
                'start_date' => now()->toDateString(),
                'end_date' => now()->addDays($validated['duration'] - 1)->toDateString(),
                'ai_itinerary' => $tripPlan, // حفظ النص المولّد
            ]);

            // 5. التوجيه إلى صفحة عرض الرحلة المحفوظة
            return redirect()->route('trip.show', $trip->id)->with('success', 'Trip successfully generated by AI and saved!');

        } else {
            // خطأ في API أو المفتاح مفقود
            return back()->withErrors(['api_error' => 'فشل الاتصال بخدمة الذكاء الاصطناعي. تأكدي من مفتاح Groq API.']);
        }
    }
    
    /**
     * دالة عرض الرحلة (يجب أن تكون موجودة في TripController أو ننشئها هنا مؤقتاً)
     *
     * @param Trip $trip
     * @return \Illuminate\Http\Response
     */
    public function show(Trip $trip)
    {
        // هذه الدالة يفترض أن تكون في TripController، لكن نضعها هنا للتوضيح
        // يجب أن ننشئ view باسم trips.show
        return view('trips.show', compact('trip'));
    }
}